
language: cpp
env:
  - DB=mysql
  - GIT_SOURCES_NRPE="https://github.com/NagiosEnterprises/nrpe/archive/master.tar.gz"
jobs:
 include:
   - os: linux
    name: Linux arm64
    arch: arm64
    dist: focal
    compiler: gcc
    script:
     - qmake -v
     - wget --no-check-certificate -O /tmp/master-nrpe.tar.gz ${GIT_SOURCES_NRPE}
     - tar xzf /tmp/master-nrpe.tar.gz -C /tmp"
     - cd /tmp/nrpe-master && ./configure --enable-command-args
     - cd /tmp/nrpe-master && make all