language: ruby

services:
  - docker

env:
  image="debian:buster"

before_install:
  - docker build -t ${image}
  - docker run -d ${image} /bin/sh -c "apt-get update && apt-get -y install autoconf gcc"
#  - docker ps -a
#  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

#script:
#  - bundle exec rake test